//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleXML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XML_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error-{0} : {1}.
        /// </summary>
        internal static string Connection_fail_msg {
            get {
                return ResourceManager.GetString("Connection_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance name is empty !
        ///If there&apos;s more than one instance running in the remote server, the connection might fail !.
        /// </summary>
        internal static string DatabaseConnection_emptyInstance_msg {
            get {
                return ResourceManager.GetString("DatabaseConnection_emptyInstance_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns mismatch error.
        /// </summary>
        internal static string IEDatabase_columns_mismatch {
            get {
                return ResourceManager.GetString("IEDatabase_columns_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export to a table with different columns !.
        /// </summary>
        internal static string IEDatabase_columns_mismatch_msg {
            get {
                return ResourceManager.GetString("IEDatabase_columns_mismatch_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to database. Please make sure your database is reachable and try again !.
        /// </summary>
        internal static string IEDatabase_connectionFail_msg {
            get {
                return ResourceManager.GetString("IEDatabase_connectionFail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to database &quot;{0}&quot; !.
        /// </summary>
        internal static string IEDatabase_successConnection_msg {
            get {
                return ResourceManager.GetString("IEDatabase_successConnection_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table successfully exported to database table &quot;{0}&quot; !.
        /// </summary>
        internal static string IEDatabase_successExport_msg {
            get {
                return ResourceManager.GetString("IEDatabase_successExport_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a document from without specifying a database table !.
        /// </summary>
        internal static string XML_ImportTable_noColumns_msg {
            get {
                return ResourceManager.GetString("XML_ImportTable_noColumns_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column already exists !.
        /// </summary>
        internal static string XML_NewTable_addExistingColumn_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_addExistingColumn_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column name provided !.
        /// </summary>
        internal static string XML_NewTable_invalidColumnName_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_invalidColumnName_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given entity name : &quot;{0}&quot; is invalid !
        ///Would you like to use &quot;data&quot; instead ?.
        /// </summary>
        internal static string XML_NewTable_invalidEntityName_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_invalidEntityName_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given entity name : &quot;{0}&quot; is invalid !
        ///Would you like to use &quot;{0}&quot; instead ?.
        /// </summary>
        internal static string XML_NewTable_invalidImportEntityName_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_invalidImportEntityName_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a table without specifying its columns !.
        /// </summary>
        internal static string XML_NewTable_noColumns_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_noColumns_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string XMLGUI__fail {
            get {
                return ResourceManager.GetString("XMLGUI__fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unsaved - {0}].
        /// </summary>
        internal static string XmlGUI__Unsaved_new_title {
            get {
                return ResourceManager.GetString("XmlGUI__Unsaved_new_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string XMLGUI__warning {
            get {
                return ResourceManager.GetString("XMLGUI__warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Excel Sheets (*.csv)|*.csv.
        /// </summary>
        internal static string XMLGUI_csvfile_extension {
            get {
                return ResourceManager.GetString("XMLGUI_csvfile_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many files were dropped!
        ///Only the first selected will be opened..
        /// </summary>
        internal static string XmlGUI_DragDrop_many_msg {
            get {
                return ResourceManager.GetString("XmlGUI_DragDrop_many_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dropped file is not an XML Document nor an Excel Sheet !.
        /// </summary>
        internal static string XmlGUI_DragDrop_wrongExt_msg {
            get {
                return ResourceManager.GetString("XmlGUI_DragDrop_wrongExt_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string XmlGUI_exit {
            get {
                return ResourceManager.GetString("XmlGUI_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this window ?
        ///Unsaved progress might be lost !.
        /// </summary>
        internal static string XmlGUI_exit_msg {
            get {
                return ResourceManager.GetString("XmlGUI_exit_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dropped file is not an XML Document !.
        /// </summary>
        internal static string XmlGUI_Open_wrongXmlExt_msg {
            get {
                return ResourceManager.GetString("XmlGUI_Open_wrongXmlExt_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open selected file !
        ///Please make sure the selected file is a simple valid XML Document / Excel Sheet..
        /// </summary>
        internal static string XmlGUI_OpenDoc_fail_msg {
            get {
                return ResourceManager.GetString("XmlGUI_OpenDoc_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open selected file !
        ///Please make sure the selected file is a valid Excel Sheet..
        /// </summary>
        internal static string XmlGUI_OpenXlsSheet_fail_msg {
            get {
                return ResourceManager.GetString("XmlGUI_OpenXlsSheet_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open selected file !
        ///Please make sure the selected file is a valid XML Document..
        /// </summary>
        internal static string XmlGUI_OpenXmlDoc_fail_msg {
            get {
                return ResourceManager.GetString("XmlGUI_OpenXmlDoc_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit all opened windows ?
        ///Unsaved progress might be lost !.
        /// </summary>
        internal static string XmlGUI_quit_msg {
            get {
                return ResourceManager.GetString("XmlGUI_quit_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t export to CSV file !.
        /// </summary>
        internal static string XMLGUI_saveCSV_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveCSV_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully saved to .
        /// </summary>
        internal static string XMLGUI_saveCurrent_success {
            get {
                return ResourceManager.GetString("XMLGUI_saveCurrent_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export an empty table !
        ///Please create a new document using &quot;File &gt; New (Ctrl + N)&quot; or open an existing one !.
        /// </summary>
        internal static string XMLGUI_saveEmptyTable_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveEmptyTable_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save data to {0} !.
        /// </summary>
        internal static string XmlGUI_saveFile_fail_msg {
            get {
                return ResourceManager.GetString("XmlGUI_saveFile_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t export to Excel Sheet xls file !.
        /// </summary>
        internal static string XMLGUI_saveXls_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveXls_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save while on read only mode !
        ///Disable read only mode and try again..
        /// </summary>
        internal static string XMLGUI_saveXml_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveXml_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file (*.xml)|*.xml|Excel xlsx Sheet (*.xlsx)|*.xlsx|Excel xls (97-2003) sheet (*.xls)|*.xls|CSV Excel Sheet (*.csv)|*.csv.
        /// </summary>
        internal static string XMLGUI_supportedFiles_extension {
            get {
                return ResourceManager.GetString("XMLGUI_supportedFiles_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Documents / Excel Tables|*.xml;*.xlsx;*.xls;*.csv|XML files (*.xml)|*.xml|Excel xlsx Sheets (*.xlsx)|*.xlsx|Excel xls (97-2003) sheets (*.xls)|*.xls|CSV Excel Sheets (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string XMLGUI_supportedfiles_opendialogExtension {
            get {
                return ResourceManager.GetString("XMLGUI_supportedfiles_opendialogExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleXML - .
        /// </summary>
        internal static string XmlGUI_title_ {
            get {
                return ResourceManager.GetString("XmlGUI_title_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel xlsx Sheets (*.xlsx)|*.xlsx|Excel xls (97-2003) sheets (*.xls)|*.xls|CSV Excel Sheets (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string XMLGUI_xlsfile_dialogextension {
            get {
                return ResourceManager.GetString("XMLGUI_xlsfile_dialogextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Sheets (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string XMLGUI_xlsfile_extention {
            get {
                return ResourceManager.GetString("XMLGUI_xlsfile_extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string XMLGUI_xmlfile_dialogextension {
            get {
                return ResourceManager.GetString("XMLGUI_xmlfile_dialogextension", resourceCulture);
            }
        }
    }
}
