//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XML_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Excel Sheets (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string XMLGUI_csvfile_dialogextention {
            get {
                return ResourceManager.GetString("XMLGUI_csvfile_dialogextention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string XmlGUI_exit {
            get {
                return ResourceManager.GetString("XmlGUI_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?
        ///Unsaved progress might be lost !.
        /// </summary>
        internal static string XmlGUI_exitmsg {
            get {
                return ResourceManager.GetString("XmlGUI_exitmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t export to CSV file!
        ///Please make sure the chosen file is not open by some other process and try again..
        /// </summary>
        internal static string XMLGUI_saveCSV_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveCSV_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully saved to .
        /// </summary>
        internal static string XMLGUI_saveCurrent_success {
            get {
                return ResourceManager.GetString("XMLGUI_saveCurrent_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export an empty table !
        ///Please create a new document using &quot;File &gt; New (Ctrl + N)&quot; or open an existing one !.
        /// </summary>
        internal static string XMLGUI_saveEmptyXml_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveEmptyXml_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string XMLGUI_saveXml_fail {
            get {
                return ResourceManager.GetString("XMLGUI_saveXml_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save while on read only mode !
        ///Disable read only mode and try again..
        /// </summary>
        internal static string XMLGUI_saveXml_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveXml_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML-GUI - .
        /// </summary>
        internal static string XmlGUI_title_ {
            get {
                return ResourceManager.GetString("XmlGUI_title_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string XMLGUI_xmlfile_dialogextention {
            get {
                return ResourceManager.GetString("XMLGUI_xmlfile_dialogextention", resourceCulture);
            }
        }
    }
}
