//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_GUI.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XML_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string XMLGUI_saveCurrent_success {
            get {
                return ResourceManager.GetString("XMLGUI_saveCurrent_success", resourceCulture);
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string XMLGUI_xmlfile_dialogextention {
            get {
                return ResourceManager.GetString("XMLGUI_xmlfile_dialogextention", resourceCulture);
            }
        }
        
        internal static string XMLGUI_xlsfile_dialogextention {
            get {
                return ResourceManager.GetString("XMLGUI_xlsfile_dialogextention", resourceCulture);
            }
        }
        
        internal static string XMLGUI_saveXml_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveXml_fail_msg", resourceCulture);
            }
        }
        
        internal static string XMLGUI__fail {
            get {
                return ResourceManager.GetString("XMLGUI__fail", resourceCulture);
            }
        }
        
        internal static string XMLGUI_saveEmptyXml_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveEmptyXml_fail_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_title_ {
            get {
                return ResourceManager.GetString("XmlGUI_title_", resourceCulture);
            }
        }
        
        internal static string XMLGUI_csvfile_dialogextention {
            get {
                return ResourceManager.GetString("XMLGUI_csvfile_dialogextention", resourceCulture);
            }
        }
        
        internal static string XMLGUI_saveCSV_fail_msg {
            get {
                return ResourceManager.GetString("XMLGUI_saveCSV_fail_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_exit_msg {
            get {
                return ResourceManager.GetString("XmlGUI_exit_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_exit {
            get {
                return ResourceManager.GetString("XmlGUI_exit", resourceCulture);
            }
        }
        
        internal static string XMLGUI__warning {
            get {
                return ResourceManager.GetString("XMLGUI__warning", resourceCulture);
            }
        }
        
        internal static string XmlGUI_OpenXmlDoc_fail_msg {
            get {
                return ResourceManager.GetString("XmlGUI_OpenXmlDoc_fail_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_OpenXlsSheet_fail_msg {
            get {
                return ResourceManager.GetString("XmlGUI_OpenXlsSheet_fail_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_Open_wrongXmlExt_msg {
            get {
                return ResourceManager.GetString("XmlGUI_Open_wrongXmlExt_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_DragDrop_wrongExt_msg {
            get {
                return ResourceManager.GetString("XmlGUI_DragDrop_wrongExt_msg", resourceCulture);
            }
        }
        
        internal static string XmlGUI_DragDrop_many_msg {
            get {
                return ResourceManager.GetString("XmlGUI_DragDrop_many_msg", resourceCulture);
            }
        }
        
        internal static string XML_NewTable_addExistingColumn_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_addExistingColumn_msg", resourceCulture);
            }
        }
        
        internal static string XML_NewTable_noColumns_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_noColumns_msg", resourceCulture);
            }
        }
        
        internal static string XML_NewTable_invalidColumnName_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_invalidColumnName_msg", resourceCulture);
            }
        }
        
        internal static string XML_NewTable_invalidEntityName_msg {
            get {
                return ResourceManager.GetString("XML_NewTable_invalidEntityName_msg", resourceCulture);
            }
        }
    }
}
